const generateEmailTemplate = (formData, source) => {
    const timestamp = new Date().toLocaleString('en-IN', {
        timeZone: 'Asia/Kolkata'
    });

    // HTML Template
    const htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            .header { background: #f4f4f4; padding: 15px; border-radius: 5px; }
            .content { margin: 20px 0; }
            table { border-collapse: collapse; width: 100%; }
            th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
            th { background-color: #f2f2f2; }
            .footer { margin-top: 20px; font-size: 12px; color: #666; }
        </style>
    </head>
    <body>
        <div class="header">
            <h2>🔔 New Form Submission</h2>
            <p><strong>Source:</strong> ${source}</p>
            <p><strong>Time:</strong> ${timestamp}</p>
        </div>
        
        <div class="content">
            <table>
                <thead>
                    <tr>
                        <th>Field</th>
                        <th>Value</th>
                    </tr>
                </thead>
                <tbody>
                    ${Object.entries(formData)
                        .filter(([key]) => !['source', '_honeypot'].includes(key))
                        .map(([key, value]) => `
                            <tr>
                                <td><strong>${key}:</strong></td>
                                <td>${value}</td>
                            </tr>
                        `).join('')}
                </tbody>
            </table>
        </div>
        
        <div class="footer">
            <p>This email was automatically generated by Universal Form Handler.</p>
        </div>
    </body>
    </html>
    `;

    // Plain text version
    const textContent = `
New Form Submission

Source: ${source}
Time: ${timestamp}

Form Data:
${Object.entries(formData)
    .filter(([key]) => !['source', '_honeypot'].includes(key))
    .map(([key, value]) => `${key}: ${value}`)
    .join('\n')}

---
This email was automatically generated by Universal Form Handler.
    `;

    return {
        html: htmlContent,
        text: textContent
    };
};

module.exports = { generateEmailTemplate };
